---
title: "Exercise2-1"
author: "A104260086"
date: "2018年11月13日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
my_height <- 170 
my_height

my_weight <- 65
my_weight

bmi <- (my_weight) / (my_height / 100)^2
bmi

my_name <- "張宜森"
my_name


beyond_start <- as.Date(date_of_origin + 5112)
beyond_start

as.integer(date_of_origin + 5112)
as.integer

beyond_start <- as.Date(date_of_origin + 5112)
beyond_start

days_diff <- as.integer(sys_date) - as.integer(date_of_origin + 5112) # 計算天數差距
days_diff

years_diff <- days_diff / 365 # 除以 365 換算成年
years_diff


major_quake_time <- as.POSIXct("1999-09-21 01:47:16" ,  tz = "GMT")
major_quake_time

first_aftershock_time <- as.POSIXct("1999-09-21 01:57:15" ,  tz = "GMT")
first_aftershock_time

major_quake_time <- as.POSIXct("1999-09-21 01:47:16" ,  tz = "GMT")
first_aftershock_time <- as.POSIXct("1999-09-21 01:57:15" ,  tz = "GMT")
as.integer(first_aftershock_time - major_quake_time)


weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
favorite_day <- weekdays[5]
favorite_day

weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
not_blue_monday <- weekdays != "Monday"
without_monday <- weekdays[1]
without_monday


speed_char <- c("slow", "fast")
speed_factor <- factor(speed_char, ordered = TRUE, levels = c("slow", "fast"))
speed_factor


my_mat <- matrix(1:9, nrow = 3)
my_mat[ 2 , 3 ]

my_mat <- matrix(1:9, nrow = 3)
filter <- my_mat %% 2 == 1
my_mat[filter]

team_name <- c("Chicago Bulls", "Golden State Warriors")
wins <- c(72, 73)
losses <- c(10, 9)
is_champion <- c(TRUE, FALSE)
season <- c("1995-96", "2015-16")
great_nba_teams <- data.frame(team_name, wins, losses, is_champion, season, stringsAsFactors = FALSE)
# 利用 `$變數名稱`
great_nba_teams$is_champion
# 利用`[, "變數名稱"]`
great_nba_teams[, "is_champion"]


my_arr <- array(1:1000, dim = c(10, 10, 10))
my_arr[ 5 , 2, 4 ]

title <- "Worst NBA Teams"
teams <- c("Charlotte Bobcats", "Philadelphia 76ers")
wins <- c(7, 9)
losses <- c(59, 73)
worst_nba_teams <- list(title, teams, wins, losses)
worst_nba_teams[[3]]


title <- "Worst NBA Teams"
teams <- c("Charlotte Bobcats", "Philadelphia 76ers")
wins <- c(7, 9)
losses <- c(59, 73)
worst_nba_teams <- list(a = title, b = teams,c = wins, d = losses)
worst_nba_teams$b

