---
title: "Untitled"
author: '123'
date: "2018年10月12日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
score<-59
if(score>=60){
 print("及格")
}else{
 print("不及格")
}
score<-80
if(score>=60){
 print("及格")
}else{
 print("不及格")
}
```

```{r}
weather <- sample(c("sunny", "rainy"), size = 1)
weather
if (weather == "sunny"){
 print("Running outdoors!")
} else {
 print("Working out in the gym!")
}
```

```{r}
my_seq <- 1:10
for (i in my_seq) {
 if (i %% 2 == 0) {
 print(paste(i, "是偶數"))
 } else {
 print(paste(i, "是奇數"))
 }
}
```

```{r}
weather <- sample(c("sunny", "rainy", "cloudy"), size = 1)
weather
if (weather == "sunny"){
 print("Running outdoors!")
} else if (weather == "cloudy"){
 print("Cycling!")
} else {
 print("Working out in the gym!")
}


```

```{r}
score<-95
if(score>=90){
 print("優秀")
}else if(score>=60){
 print("及格")
}else{
 print("不及格")
}
```
```{r}
my_seq <- 1:10
for (i in my_seq) {
 if (i %% 3 == 0) {
 print(paste(i, "可以被 3 整除"))
 } else if (i %% 3 == 1) {
 print(paste(i, "除以 3 餘數是 1"))
 } else {
 print(paste(i, "除以 3 餘數是 2"))
 }
}
```
```{r}
CHscore<-95 ##國???成績
ENscore<-55 ##英???成績
if(CHscore>=60){
 if(ENscore>=60){
 print("全部及格")
 }else{
 print("國???及格，英???再加油")
 }
}else{
 if(ENscore>=60){
 print("英???及格，國???再加油")
 }else{
 print("全部不及格")
 }
}
```

```{R}
score<-80
ifelse(score>=60,"及格","不及格")
scoreVector<-c(30,90,50,60,80)
ifelse(scoreVector>=60,"及格", "不及格")
```
```{R}
for (n in 1:10){
 #n為單???變數，1:10為需要逐???執???的參數向量
 print(n)
}
```
```{R}
for (month in month.name){
 print(month)
}
```
```{r}
x <- 0
while (x<=5) {
 print(x)
 x<-x+1
}
```
```{r}
i <- 1
while (i < 13){
 print(month.name[i])
 i <- i + 1
}
```
```{r}
flip_results <- c() # 建立???個空的向量來放置每???次投擲的結果
coin <- c(TRUE, FALSE) # TRUE 代表正???，FALSE 代表反???
n_flips <- 1 # 從第???次投擲開始記錄
while (sum(flip_results) < 3){
 flip_results[n_flips] <- sample(coin, size = 1) # 將每次投擲結果記錄起來
 n_flips <- n_flips + 1 # 準備記錄下???次的投擲結果
}
flip_results # 印出每次投擲的紀錄
length(flip_results) # 總共投擲了幾次

```
```{r}
for (n in 1:10){
 if(n%%2==0){ #偶數直接輸出數字
 print(n)
 }else{
 print("奇數") #奇數則輸出"奇數"
 }
}
```
```{r}
for (month in month.name){
 if (month == "April"){
 break
 } else {
 print(month)
 }
}
```
```{r}
abs(-5)
abs(-5:-1)
abs("Hello")
```
```{r}
sqrt(2)
sqrt(1:10)
```
```{r}
ceiling(9.527)
nums <- sqrt(c(7, 17, 27, 37, 47))
nums
ceiling(nums)
```
```{r}
floor(9.527)
nums <- sqrt(c(7, 17, 27, 37, 47))
nums
floor(nums)
```
```{r}
round(9.527)
round(9.527, digits = 0)
round(9.527, digits = 1)
round(9.527, digits = 2)
```
```{r}
log(exp(1))
log(exp(2))
log(exp(3))
```
```{r}
log10(10)
log10(10^2)
log10(10^3)
```
```{r}
toupper("Learn R the easy way")
```
```{r}
tolower("Learn R the easy way")
```
```{r}
my_char <- "Learn R the easy way"
substr(my_char, start = 1, stop = 5)
substr(my_char, start = 7, stop = 7)
substr(my_char, start = 9, stop = 11)
substr(my_char, start = 13, stop = 16)
substr(my_char, start = 18, stop = 20)
```
```{r}
my_char <- c("Learn", "R", "the", "easy", "way")
grep(pattern = "Learn", my_char)
grep(pattern = "R", my_char)
grep(pattern = "the", my_char)
grep(pattern = "easy", my_char)
grep(pattern = "way", my_char)
grep(pattern = "xyz", my_char)
```
```{r}
my_char <- c("Learn", "R", "the", "easy", "way")
grep(pattern = "learn", my_char)
integer(0)
grep(pattern = "learn", my_char, ignore.case = TRUE)
```
```{r}
my_char <- c("Learn", "R", "the", "easy", "way")
sub(pattern = "easy", replacement = "effortless", my_char)
my_char <- c("Learn", "R", "the", "easy", "way")
sub(pattern = "EASY", replacement = "effortless", my_char)
sub(pattern = "EASY", replacement = "effortless", my_char, ignore.case = TRUE)
```

```{r}
my_char <- "Learn R the easy way"
strsplit(my_char, split = " ") # 使??????個空格作為切割的根據

my_char <- "Learn,R,the,easy,way"
strsplit(my_char, split = ",") # 使??????個逗號作為切割的根據

```
```{r}
char_1 <- "Learn"
char_2 <- "R"
char_3 <- "the"
char_4 <- "easy"
char_5 <- "way"
paste(char_1, char_2, char_3, char_4, char_5)
paste(char_1, char_2, char_3, char_4, char_5, sep = ",")
paste(char_1, char_2, char_3, char_4, char_5, sep = "")
```
```{r}
my_seq <- 1:5
mean(my_seq)
my_seq <- c(my_seq, NA) # 加入???個 NA
mean(my_seq) # 輸出為 NA
mean(my_seq, na.rm = TRUE) # 排除遺漏值
```
```{r}
my_seq <- 1:5
mean(my_seq)
my_seq <- c(my_seq, NA) # 加入???個 NA
mean(my_seq) # 輸出為 NA
mean(my_seq, na.rm = TRUE) # 排除遺漏值
```
```{r}
my_seq <- 1:5
sd(my_seq)
my_seq <- c(my_seq, NA) # 加入???個 NA
sd(my_seq)
sd(my_seq, na.rm = TRUE) # 排除遺漏值
```
```{r}
my_seq <- 1:5
median(my_seq)
my_seq <- c(my_seq, NA) # 加入???個 NA
median(my_seq)
median(my_seq, na.rm = TRUE) # 排除遺漏值
```
```{r}
my_seq <- 1:5
range(my_seq)
my_seq <- c(my_seq, NA) # 加入???個 NA
range(my_seq)
range(my_seq, na.rm = TRUE) # 排除遺漏值
```
```{r}
my_seq <- 1:5
sum(my_seq)
my_seq <- c(my_seq, NA) # 加入???個 NA
sum(my_seq)
sum(my_seq, na.rm = TRUE) # 排除遺漏值
```
```{r}
my_seq <- 1:5
max(my_seq)
my_seq <- c(my_seq, NA) # 加入???個 NA
max(my_seq)
max(my_seq, na.rm = TRUE) # 排除遺漏值
```
```{r}
my_seq <- 1:5
min(my_seq)
my_seq <- c(my_seq, NA) # 加入???個 NA
min(my_seq)
min(my_seq, na.rm = TRUE) # 排除遺漏值
```

```{r}
# ???訂函數
my_squared <- function(x){
 y <- x^2
 return(y)
 }
# 呼叫函數
my_squared(2)
my_squared(-2:2)
```
```{r}
# ???訂函數
circle_area <- function(r){
 area <- pi * r^2 # R 語???有內建圓周率 pi
 return(area)
 }
# 呼叫函數
circle_area(3)
circle_area(5)
```
```{r}
# ???訂函數
circle_circum <- function(r){
 circum <- 2 * pi * r # R 語???有內建圓周率 pi
 return(circum)
 }
# 呼叫函數
circle_circum(3)
circle_circum(5)
```
```{r}
# ???訂函數
circle_calculator <- function(r, is_area){
 area <- pi * r^2
 circum <- 2 * pi * r
 if (is_area == TRUE){
 return(area)
 } else {
 return(circum)
 }
 }
# 呼叫函數
circle_calculator(3, is_area = TRUE)
circle_calculator(3, is_area = FALSE)
```
```{r}
># ???訂函數
> ......
># 呼叫函數
>circle_calculator(3)
Error in circle_calculator(3) :
 argument "is_area" is missing, with no default
```

```{r}
> # ???訂函數
> circle_calculator <- function(r, is_area = TRUE){
+ ...
+ }
> # 呼叫函數
> circle_calculator(3)
[1] 28.27433
```
```{r}
# ???訂函數
my_length <- function(x){
 counts <- 0
 for (i in x){
 counts <- counts + 1
 }
 return(counts)
 }
# 建立???個向量
 my_vec <- seq(from = 15, to = 87, by = 3)
# 呼叫內建（外部）與???訂函數
length(my_vec)
my_length(my_vec)
```
```{r}
# ???訂函數
my_sum <- function(x){
 summation <- 0
 for (i in x){
 summation <- summation + i
 }
 return(summation)
 }
# 呼叫內建與???訂函數
sum(1:10)
my_sum(1:10)
```
```{r}
# 定義???訂函數
my_mean <- function(input_vector) {
 my_sum <- function(input_vector) {
 temp_sum <- 0
 for (i in input_vector) {
 temp_sum <- temp_sum + i
 }
 return(temp_sum)
 }
 my_length <- function(input_vector) {
 temp_length <- 0
 for (i in input_vector) {
 temp_length <- temp_length + 1
 }
 return(temp_length)
 }
 return(my_sum(input_vector) / my_length(input_vector))
}
# 呼叫???訂函數
my_vector <- c(51, 8, 18, 13, 6, 64)
my_mean(my_vector)
```


